version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing backend dependencies...
      - cd server
      - npm install
      - echo Making scripts executable...
      - chmod +x scripts/*.sh || echo "No scripts to chmod"

  build:
    commands:
      - echo No build step required for backend, skipping...

  post_build:
    commands:
      - echo Copying backend files to deployment folder...
      - rm -rf /home/ec2-user/fastkart/backend/*
      - cp -R server/* /home/ec2-user/fastkart/backend/

artifacts:
  files:
    - '**/*'
    - '!package-lock.json'
  discard-paths: no


